export const CURRENT_WEATHER_LOADING = 'CURRENT_WEATHER_LOADING'
export const CURRENT_WEATHER_SUCCESS = 'CURRENT_WEATHER_SUCCESS'
export const CURRENT_WEATHER_ERROR = 'CURRENT_WEATHER_ERROR'

export const FIVE_DAY_FORECAST_LOADING = 'FIVE_DAY_FORECAST_LOADING'
export const FIVE_DAY_FORECAST_SUCCESS = 'FIVE_DAY_FORECAST_SUCCESS'
export const FIVE_DAY_FORECAST_ERROR = 'FIVE_DAY_FORECAST_ERROR'

export const CITY_LIST_PUSH = 'CITY_LIST_PUSH'
export const CITY_LIST_ERROR = 'CITY_LIST_ERROR'
export const CITY_LIST_LOADING = 'CITY_LIST_LOADING'
export const CITY_LIST_REMOVE = 'CITY_LIST_REMOVE'